- name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com 
          server_port: 587                   
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Daily Market Update
          html_body: file://news_body.txt
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: "Daily Bot <your-actual-email@example.com>" # Type your actual email here
